### ISSUE TITLE
🤗 [Question]: Could you mint a new release?

### ISSUE THREAD

**Issue by gzuidhof** [gofiber/contrib#1086]
### Question Description

Would it perhaps be possible to mint/tag a new release from current `main`? The last release (`1.0.0`) was over a month ago on March 7th.

Thank you :)

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
@gzuidhof for which package ?

**Comment by ReneWerner87** [comment]
![image](https://github.com/gofiber/contrib/assets/7063188/ab661e4d-6aa7-460b-a8ee-b6559ca33ff5)
![image](https://github.com/gofiber/contrib/assets/7063188/95936d5a-d3cb-4c91-bede-56d6f133d200)

ok i just pushed everything :D

**Comment by gzuidhof** [comment]
Thank you! :)
