### ISSUE TITLE
🤗 [Question]: How does socketio differentiate between TextMessage and BinaryMessage?

### ISSUE THREAD

**Issue by liaohongxing** [gofiber/contrib#1114]
### Question Description

@antoniodipinto 

### Code Snippet (optional)

```go
socketio.On(socketio.EventMessage, func(ep *socketio.EventPayload) {
	fmt.Println("==EventMessage==", string(ep.Data))

	if (TextMessage) {
		//TextMessage
	}
	if (BinaryMessage) {
		//BinaryMessage
	}
})
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by antoniodipinto** [comment]
Hi @liaohongxing here's how socketio manages this. By default websocket protocol defines the datatype. More information about this can be found here https://www.rfc-editor.org/rfc/rfc6455.html#section-11.8

Code reference Gorilla WebSocket https://github.com/gorilla/websocket/blob/main/conn.go#L61
Code reference for socketio fiber https://github.com/gofiber/contrib/blob/main/socketio/socketio.go#L16

**Comment by liaohongxing** [comment]
Thanks for your quick response, I read your tip carefully.

The EventPayload callback seems to lack a flag to distinguish the two message types

For example, I want to receive messages and files in the callback, how can I do it?

**Comment by antoniodipinto** [comment]
Hi @liaohongxing as I mentioned, there is no need to check the message type, because this implementation supports only WebsocketMessageType = 1 (Text Message).
The solution for your problem can be pretty simple using Base64 to encode the file, depending on your implementation.

**Comment by liaohongxing** [comment]
Well. I think I know how to do it. thank you
