### ISSUE TITLE
🤗 [Question]: Is there any updates about fiber v3 support for middlewares such a otelfiber?

### ISSUE THREAD

**Issue by defany** [gofiber/contrib#1141]
### Question Description

I was checking other issues about unsupporting middlewares for fiber v3

Is there any news about it cuz I can't find any other solution for otel tracing in fiber v3 and I so don't want to go back on v2 :(

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by heisGarvit** [comment]
#1163

**Comment by gaby** [comment]
@defany v3 is still in beta, middlewares will be upgrade once we are closer to release.

**Comment by defany** [comment]
love u, ty
