### ISSUE TITLE
🤗 [Question]: Make Fiber Faster

### ISSUE THREAD

**Issue by jrCleber** [gofiber/contrib#1200]
### Question Description

I'm using **fiber**. In the [documentation](https://docs.gofiber.io/guide/faster-fiber) there is an option to make it faster, but the **Config** struct is no longer available, does this mean that this implementation is no longer needed?

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v2"
import "github.com/goccy/go-json"

func main() {
	app := fiber.New(fiber.Config{
		JSONEncoder: json.Marshal,
		JSONDecoder: json.Unmarshal,
	})

	# ...
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
Hi, sorry i missed this report. 
Hopefully you found the answer. 
The example should work on v2 and v3.
