### ISSUE TITLE
There should be an option to pass the existing NewRelic app without creating a new one

### ISSUE THREAD

**Issue by th0th** [gofiber/contrib#269]
Greetings,

Currently, NewRelic middleware requires the configuration parameters to be passed and creates a new NewRelic application. However, on the project I am working on, I already have a NewRelic app and I use it some other places as well. I totally understand the basic-friendly approach, however, can we also have a function something like `fibernewrelic.NewWithApp(app *newrelic.Application)` that enables using the existing app? If so, I can start a PR that implements such a change.

**Comment by efectn** [comment]
You can add a field to config typed `*newrelic.Application` into the https://github.com/gofiber/contrib/blob/main/fibernewrelic/fiber.go#L10 and if it was given it overrides another fields. Feel free to contribute ☺️
