### ISSUE TITLE
move "bad: missing PASETO token" to helpers.go

### ISSUE THREAD

**Issue by liaohongxing** [gofiber/contrib#4]
https://github.com/gofiber/contrib/blob/dab972f859dd3d9a2032b5c86780c667f833ee2a/paseto/paseto.go#L35

errors.New("bad: missing PASETO token")   moved to helpers.go#L22 ，so that "errors.Is"

https://github.com/gofiber/contrib/blob/dab972f859dd3d9a2032b5c86780c667f833ee2a/paseto/helpers.go#L22

@Jictyvoo

**Comment by Jictyvoo** [comment]
I don't understand your issue well. You requesting to move this error to `helpers.go`?

**Comment by liaohongxing** [comment]
example code
```
ErrorHandler: func(c *Ctx, err) error {
   if errors.Is(paseto.ErrMissingToken) {
      return c.JSON(fiber.Map{"MissingTokenLang": "I18n"});
      // or
      return c.Redirect("/signin")
   }
}
```

**Comment by Jictyvoo** [comment]
I see, ok, I gonna make a pull request to improve this
