### ISSUE TITLE
OTel: add method to span name

### ISSUE THREAD

**Issue by morigs** [gofiber/contrib#47]
Currently, otel middleware [sets](https://github.com/gofiber/contrib/blob/97ea1c071d84861407b9867b0d569c6a70ee27c2/otelfiber/fiber.go#L84) span name to route path. However, it's possible to register multiple routes with the same path but different methods. For example, `POST /orders` and `GET /orders`.
I believe, span name should include method along with path.

**Comment by WLun001** [comment]
@morigs I think do not need to set method name to span name, as the attributes already set. It works fine with Tracing service
![image](https://user-images.githubusercontent.com/23547929/149257213-71b3ffd4-8e3b-4bc3-80de-7c6696f36bd3.png)

**Comment by morigs** [comment]
@WLun001 on your screenshot, there is method name in span name. Is it from the instrumentation from this repo? Because I cannot find where it adds method to span name

**Comment by WLun001** [comment]
the method name adds from here, not from span name
https://github.com/gofiber/contrib/blob/97ea1c071d84861407b9867b0d569c6a70ee27c2/otelfiber/fiber.go#L57

**Comment by morigs** [comment]
What tracing tool do you use? For example, Jaeger groups all spans in "operations" by span names. This means that all spans with name "/users/id" will be in one operation, even if they have different attributes. This is confusing and complicates search

**Comment by WLun001** [comment]
I am testing with https://uptrace.dev/, could you share your screenshot with Jaeger? I never use it before

**Comment by morigs** [comment]
@WLun001 In Jaeger it looks like this. As you can see, there is no method in operation name. So all paths with different methods are grouped together

![image](https://user-images.githubusercontent.com/13474134/149294779-c4328d15-f48e-4120-b5c9-a245d5fa68eb.png)

**Comment by WLun001** [comment]
@morigs I think we can do something like this to allow custom format. What do you think?

https://github.com/open-telemetry/opentelemetry-go-contrib/blob/7e31ebe040306aee2c826972269f938f9f0e7c34/instrumentation/net/http/otelhttp/config.go#L175

**Comment by morigs** [comment]
@WLun001 sounds good. However, I think that span name should include method name by default, because Jaeger is very popular and other tracing systems works similarly.
Span name should specific enough to identify specific operation. OpenTelemetry semantic conventions mention this as a best practice.

**Comment by WLun001** [comment]
@morigs not sure if we should do that. If you look at current implementation, they did not include method name
https://github.com/open-telemetry/opentelemetry-go-contrib/tree/7e31ebe040306aee2c826972269f938f9f0e7c34/instrumentation

**Comment by morigs** [comment]
@WLun001 
Not really. `otelhttp.NewHandler` accepts user-specified name of the span through `operation` parameter. So it's up to the user to specify a name that specific enough to identify the handler. 
For example, I can use it this way: `otelhttp.NewHandler(postHandler, "create-enitity")` and `otelhttp.NewHandler(deleteHandler, "delete-enitity")`.
However, gofiber instrumentation doesn't require operation name, it sets the name to the route path by default, what causes problems.
Spec [describes](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#span) recommended span names. Example from spec: `get_account`, not just `account`.
I understand your point, just making my point clear. If you think that custom formatter will be enough, well, OK. That solves the problem, that's what matters.
