### ISSUE TITLE
Prefix version tags with module names

### ISSUE THREAD

**Issue by database64128** [gofiber/contrib#470]
According to https://go.dev/doc/modules/managing-source#multiple-module-source, when you have multiple modules in a single repository, version tags must have the module name as a prefix. Otherwise, attempting to use tagged versions would fail:

```console
❯ go get github.com/gofiber/contrib/fiberzap@v1.0.1
go: module github.com/gofiber/contrib@v1.0.1 found, but does not contain package github.com/gofiber/contrib/fiberzap
```

Instead of having a single `v1.0.1` tag, tag each module individually.

**Comment by efectn** [comment]
Yeah, same thing is also valid for storage repo. We're investigating how to do it automated and properly as aws does.
