### ISSUE TITLE
OTel: use semconv functions for filling out attributes

### ISSUE THREAD

**Issue by morigs** [gofiber/contrib#49]
Currently, otel middleware add all the attributes [manually](https://github.com/gofiber/contrib/blob/97ea1c071d84861407b9867b0d569c6a70ee27c2/otelfiber/fiber.go#L55).
I think it's better to use [semconv functions](https://pkg.go.dev/go.opentelemetry.io/otel@v1.3.0/semconv/v1.7.0) for cases when `fasthttp.Request` is compatible with `http.Request` because this will automatically add all recommended attributes. This is easier to maintain because following spec requires semconv package update only.

Besides, I think it [should use](https://github.com/open-telemetry/opentelemetry-go/issues/2296) `SpanStatusFromHTTPStatusCodeAndSpanKind` instead of `SpanStatusFromHTTPStatusCode`

**Comment by WLun001** [comment]
@morigs could you make a PR about this?

**Comment by WLun001** [comment]
@morigs fasthttp is not compatible with http
https://github.com/valyala/fasthttp#faq

**Comment by morigs** [comment]
This is very unfortunate 😞
At least, we should ensure that the set of attributes is the same

**Comment by efectn** [comment]
I think we can create same semconv methods that compatible with fasthttp.Request. But i'm not sure about that, i didn't review semconv's code much

**Comment by WLun001** [comment]
@morigs yes i have checked it. If you found out any missing attributes please feel free to create issues or PRs

**Comment by morigs** [comment]
@WLun001 awesome, thank you!
