### ISSUE TITLE
Error is not returned from otelfiber.Middleware() handler

### ISSUE THREAD

**Issue by calloway-jacob** [gofiber/contrib#532]
The middleware returned from `otelfiber.Middleware()` always returns `nil`, even if the next middleware in the stack returned an error.

When using multiple middlewares together, this can prevent a middleware earlier in the stack from also having access to the error. This is undesirable, for example, if an earlier-added logging middleware should also log the error (and which is outside of the fiber application's configured ErrorHandler).

**Comment by ReneWerner87** [comment]
@eko can you help here

**Comment by calloway-jacob** [comment]
I've just noticed that my PR introduces a regression in the test (line 146 if `fiber_test.go`

**Comment by calloway-jacob** [comment]
I suppose it is by design that this middleware catches any errors from middleware up the stack and directly invoke's the app's error handler? I see from the code comments that this is required to get the HTTP response status code to add into the tracing.

If that is the intended design, I don't see a way to make this compatible with other middlewares lower in the stack receiving access to the error additionally.

In that case, perhaps can we document that the tracing middleware should be the first one added to the stack?

**Comment by calloway-jacob** [comment]
After working quite some time trying to combine the use of `fiberzap` and `otelfiber`, I've come to the conclusion that these two package middlewares are simply not 100% compatible with one another. As both of them call the app's error handler, it is necessary to return a nil error in each package.

I have an idea of how they could be made compatible, but it would require changes in each package as well as in fiber itself, which seems unlikely to be an accepted change.

The idea itself would be to introduce a new type, `HandledError`. This would represent an error that has already been passed to the app's error handler.

Any middleware that needs to call the app's error handler (and usually return a nil error), would have to check if the error is a `HandledError`. In that case, the middleware knows that the app's error handler was already called, and can get the response code and use the error for logging/tracing/etc.. In the case that an error is not a `HandledError`, the middleware is free to call the app's error handler, but must then return a `HandledError` (wrapping the original error) to signal to other middlewares that the error handler was already called for it.

Fiber itself would also have to take part in this scheme, and avoid calling the app's error handler when a middleware returns a `HandledError`.

I doubt that the payoff would be worth it here, but it would definitely extend the ability of multiple middlewares to react to an error up the stack without the fear of accidentally running side-effects from the error handler multiple times.
