### ISSUE TITLE
Otel: add ability to override span name

### ISSUE THREAD

**Issue by morigs** [gofiber/contrib#57]
Use case: we use session middleware. When some middleware interrupts request processing before any handler invocation, the span name is always `/` which is not informative and leads to grouping of all operations ended by any middleware.
Suggestion: Fiber supports names for routes. The instrumentation could check `c.Route().Name` and if it's not empty, then use it as a span name instead of `c.Route().Path`

**Comment by WLun001** [comment]
refer https://github.com/gofiber/contrib/issues/47#issuecomment-1011978593
