### ISSUE TITLE
Otel v1.15.1 breaking changes

### ISSUE THREAD

**Issue by bangbaew** [gofiber/contrib#578]
![image](https://user-images.githubusercontent.com/29559559/236730668-c6b7973b-09a5-4df3-bc9d-fe1761c0c775.png)
I've tried updating to latest commit (as of today, it's feaa1ed), but it's not able to build due to the following errors, but I've seen the dependabots updated all the otel modules to v1.15.1 and passed GitHub Actions tests in this repo, I wonder why mine is not working?

![image](https://user-images.githubusercontent.com/29559559/236731268-668a746a-3dff-4e30-b5a5-db2b08045310.png)

**Comment by ivan-penchev** [comment]
This is an issue for my team too.

**Comment by mstrYoda** [comment]
Well we might need another update: https://github.com/gofiber/contrib/pull/593#issuecomment-1559217805

**Comment by ivan-penchev** [comment]
With the merging of #613  I can safely report that this has resolved everything for us.
Maybe we should consider closing this issue now? @ReneWerner87 @gaby @mstrYoda
