### ISSUE TITLE
🚀 [Feature]: Add ability to ignore health checks in otelfiber

### ISSUE THREAD

**Issue by efumagal** [gofiber/contrib#632]
### Feature Description

Something that was done for fiberzap but for otelfiber: https://github.com/gofiber/contrib/pull/272

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my suggestion prior to opening this one.
- [X] I understand that improperly formatted feature requests may be closed without explanation.

**Comment by emanuelef** [comment]
This one can probably be closed after https://github.com/gofiber/contrib/commit/9cc7ba741b4b40457dc8ddba2309f210417414fe

**Comment by emanuelef** [comment]
Although I guess to be able to use WithNext we need a new tag/release for otelfiber, isn't it ?

**Comment by ReneWerner87** [comment]
yes, with the next release process
