### ISSUE TITLE
🤗 [Question]: swagger yaml support?

### ISSUE THREAD

**Issue by tamis-laan** [gofiber/contrib#708]
### Question Description

I'm using github.com/gofiber/contrib/swagger and would like to write my spec in yaml format. 

``` go
// Use swagger 2.0 middleware
app.Use(swagger.New(swagger.Config{
    BasePath: "/",
    FilePath: "./swagger.yaml",
}))
```
This works but in the UI the link to the file is set as `/swagger.json` not `/swagger.yaml` this causes the validator to fail:

![screenshot](https://github.com/gofiber/contrib/assets/3178666/c82f79d2-e294-410a-92c2-e33e060eea6d)
(see lower right corner in the UI)

The second question I have is, how do I deal with multiple openapi yaml files? Can we use ` FilePath: "./spec/*`?
### Code Snippet (optional)

```go
// Use swagger 2.0 middleware
app.Use(swagger.New(swagger.Config{
    BasePath: "/",
    FilePath: "./swagger.yaml",
}))
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by gaby** [comment]
@tamis-laan For question 1 yes this is a bug. I may have found why, will do a PR this week.

For question 2 the library we are using only allows one SPEC file

**Comment by gaby** [comment]
@tamis-laan I'm doing the PR today, got it working :-)
