### ISSUE TITLE
🤗 [Question]: otelfiber + otelmongo spans are not being grouped correctly

### ISSUE THREAD

**Issue by marcelobiao** [gofiber/contrib#716]
### Question Description

I recently added Opentelemetry to a project I'm involved in. My setup includes using Zipkin as the collector and Fiber (otelfiber) and MongoDB (otelmongo) instrumentation to automate the capturing of their information. However, I've been facing an issue where the generated spans are not correctly setting the Parent ID, resulting in a lack of grouping for this information.

To ease the reproduction of this behavior, I've put together a simple code. In this code, I've launched two webservers: one using the Gin framework and the other utilizing Fiber. Both servers are configured to perform trace information collection.

As a result, requests directed to the Gin service generate spans grouped correctly. However, for requests to the Fiber service, the spans are not being grouped, leading to the situation I mentioned.

![zipkin](https://github.com/gofiber/contrib/assets/8891971/efa75af2-ccd3-4cbb-bc73-3d91ac6bef18)

I would like to express my gratitude in advance for any guidance, suggestions, or insights that could be shared to assist in resolving this behavior. If anyone has encountered a similar situation or has any tips, I would be grateful for your contribution.

### Code Snippet (optional)

```go
to reproduce the error:
// Clone repo
https://github.com/marcelobiao/gofiber-otel-issues

// run local containers
$task run 

// In the browser:
Gin server:
http://localhost:8080/todo
Fiber server:
http://localhost:8081/todo

// Access Zipkin Client:
http://localhost:9411
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by joaofnds** [comment]
I just ran into the same issue, changing from `c.Context()` to `c.UserContext()` fixed it for me.

In your case, I believe that this would be in [server.go#L37](https://github.com/marcelobiao/gofiber-otel-issues/blob/main/app/server.go#L37) and [server.go#L40](https://github.com/marcelobiao/gofiber-otel-issues/blob/main/app/server.go#L40)

**Comment by gaby** [comment]
@marcelobiao Can you verify if the above fixes your issue?

**Comment by marcelobiao** [comment]
Problem solved
thanks guys!
