### ISSUE TITLE
🚀 [Feature]: otelfiber - Propergate tracing headers in outbound response

### ISSUE THREAD

**Issue by ledex** [gofiber/contrib#836]
### Feature Description

When using the otelfiber middleware it would be nice to propergate the tracing headers to the outbound response in order to unify tracing across the call-chain. It would be needed to inject the coresponding headers from the TextMapPropagator, similar to the code snippet below.

This is already done in the limiter middleware for propergating the `X-Ratelimit*` headers (also see https://github.com/gofiber/fiber/blob/master/middleware/limiter/limiter_fixed.go#L100-L102).

### Code Snippet (optional)

```go
func AddTracingHeadersToContext(ctx *fiber.Ctx) {
	var tracingHeader = make(propagation.HeaderCarrier)
	otel.GetTextMapPropagator().Inject(ctx.UserContext(), tracingHeader)

	for _, headerKey := range tracingHeader.Keys() {
		ctx.Set(headerKey, tracingHeader.Get(headerKey))
	}
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my suggestion prior to opening this one.
- [X] I understand that improperly formatted feature requests may be closed without explanation.

**Comment by ledex** [comment]
I would be able to implement this in general, but some feedback on this would be appreciated 😀

**Comment by ReneWerner87** [comment]
unfortunately i have no experience with this middleware, so i need an opinion from you
@KaptinLin @emanuelef @efumagal @mstrYoda @danielalvarenga @eko @onematchfox @ijsong @lucasoares @WLun001

**Comment by emanuelef** [comment]
Is it to be able to add the spans in the same trace across different services ?
I remember I was able to do that in case and described in an article: https://medium.com/stackademic/start-using-opentelemetry-with-go-fiber-1005697d841f.
But maybe I'm misunderstanding.

**Comment by ReneWerner87** [comment]
@ledex

**Comment by ledex** [comment]
Sorry for not replying earlier, I'm currently on vacation, but will get back to this issue/pull request on monday. 

@emanuelef I'll have a look at the article you posted and build an example of my use case for this.
