### ISSUE TITLE
🤗 [Question]: fiberzerolog the banner is not printed.

### ISSUE THREAD

**Issue by kuchaguangjie** [gofiber/contrib#985]
### Question Description

After integrate zerolog to fiber according to https://docs.gofiber.io/contrib/fiberzerolog/.
Everything works fine, except that the banner part is only printed to console, not to file, aka. not printed via zerolog.

I know zerolog print json, it might be impossible to print the banner via zerolog.
But is there a workaround for the plugin, e.g when init the middleware, print something similar as the banner via zerolog ?

This is the banner in console:

  ![image](https://github.com/gofiber/contrib/assets/4230959/fe94c897-5a72-4c1c-9d40-a6732611d224)

And it's missing in the log file:

  ![image](https://github.com/gofiber/contrib/assets/4230959/2ce417d4-d52c-4149-bb07-fd62ab94e55f)

### Code Snippet (optional)

```go
func setupLog(app *fiber.App) {
	// log via zerolog,
	app.Use(fiberzerolog.New(fiberzerolog.Config{
		Logger: log_util.GetLogger(),
	}))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by dassump** [comment]
Hi @kuchaguangjie, the banner is written only in os.Stdout.
https://github.com/gofiber/fiber/blob/109e91a630679dc7739e80ebdf8355ace8aafcd4/listen.go#L453

You need to create your own initialization message in the log, perhaps using the OnListenHandler hook.
